#!/bin/bash

log_file=/home/wjrh/robo-dj-install/log/songs.log
sql_server=10.8.0.14

# assign song artist and title variables
artist=$1
title=$2

# append the new song info to the end of the log file
echo -e "[$(date)]\t$artist\t$title" >> $log_file

# insert the new song info into the remote database
sql_string="INSERT INTO song_log (entity, title, artist) VALUES('robo-dj', '$title', '$artist');"

# Send the log command, give up if no response after 5 seconds
timeout 5 psql -h $sql_server --no-password --quiet -c "$sql_string"
